### PR TITLE
Milestone 1 

### PR DESCRIPTION
**Pull request by kensayo**
### MILESTONE 1

**Navbar, Highlights, Funding and Footer**

- Completed responsive for section mentioned before (mobile, tablet, desktop)

### CODE REVIEW

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
Hello guys, I'm super happy to see your project looking so good. Let's make few changes so that we can move.✔💪👈

1. The logo image should be a link.
2. The yellow part in the header is missing.
3. The TNW is missing in the footer paragraph area.
4. display: flex and display block has been repeated more than 9 times, try writing all the selector which require display flex or display block in one declaration.
[OPTIONAL] Disability icon also missing in your footer right corner.
Please fix this issue and submit another review request.
**Note** You only have two reviews left "As described in the Code reviews limit Policy you have 2 code reviews left for this project.
Please you can contact me on slack if you have any questions.🎉✔

**Comment by elisha2kyakpo1** [comment]
Also, check the live link, you have used a different link address

**Comment by kensayo** [comment]
> Also, check the live link, you have used a different link address

Hi, thanks for the code review. We use the link provided [in the pathright](https://perma.cc/M5ZV-Q2D6?)  for The Next Week webpage, so we base our content on that. We are not using the live website cause that's not the link provided.

**Comment by elisha2kyakpo1** [comment]
I'm sorry if my comment wasn't clear, I meant your project live link in your README file is not the Next week website but the new york times(GitHub pages) **"https://kensayo.github.io/NYT-wk1/"**

**Comment by kensayo** [comment]
> I'm sorry if my comment wasn't clear, I meant your project live link in your README file is not the Next week website but the new york times(GitHub pages) **"https://kensayo.github.io/NYT-wk1/"**

Oh ok, I get sorry I forgot to modify that. Thanks!.

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @kensayo and @fortuneonyeka :wave: 

### Thank you for making all of the requested changes. I had to check your page twice to make sure I wasn't looking at the original one! Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
